export default {
  "managers": [
    {
      "id": "1",
      "name": "Manager A",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "2",
      "name": "Manager B",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "3",
      "name": "Manager C",
      "hpc": "2.98",
      "voc": "89",
      "atnd": "300",
      "aiq": "82"
    },
  ],
  "hpc": [
    {
      "id": "1",
      "managerId": "1",
      "name": "Manager A",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "2",
      "managerId": "2",
      "name": "Manager B",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "3",
      "managerId": "3",
      "name": "Manager C",
      "hpc": "3",
      "goal": "2.15",
      "variance": "3.0",
      "varPercent": "10",
      "de": "77",
      "productivity": "75",
    },
  ],
  "voc": [
    {
      "id": "1",
      "managerId": "1",
      "name": "manager",
      "voc": "100",
      "aiq": "96",
    }
  ],
  "atnd": [
    {
      "id": "1",
      "managerId": "1",
      "name": "manager",
      "atnd": "138",
      "productivity": "82",
      "earnedHrs": "410",
      "totalHrs": "500",
    }
  ],
  "techs": [
    {
      "id": "1",
      "managerId": "1",
      "name": "Tech A",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "2",
      "managerId": "1",
      "name": "Tech B",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    }, {
      "id": "3",
      "managerId": "1",
      "name": "Tech C",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    }, {
      "id": "4",
      "managerId": "1",
      "name": "Tech D",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    }, {
      "id": "5",
      "managerId": "1",
      "name": "Tech E",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "6",
      "managerId": "1",
      "name": "Tech F",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "6",
      "managerId": "1",
      "name": "Tech G",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "7",
      "managerId": "1",
      "name": "Tech H",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "8",
      "managerId": "1",
      "name": "Tech I",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "9",
      "managerId": "1",
      "name": "Tech J",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "10",
      "managerId": "1",
      "name": "Tech K",
      "hpc": "2.98",
      "voc": "100",
      "atnd": "138",
      "aiq": "96"
    },
    {
      "id": "11",
      "managerId": "2",
      "name": "Tech L",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "12",
      "managerId": "2",
      "name": "Tech M",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    }, {
      "id": "13",
      "managerId": "2",
      "name": "Tech N",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    }, {
      "id": "14",
      "managerId": "2",
      "name": "Tech O",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    }, {
      "id": "15",
      "managerId": "2",
      "name": "Tech P",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "16",
      "managerId": "2",
      "name": "Tech Q",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "16",
      "managerId": "2",
      "name": "Tech R",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "17",
      "managerId": "2",
      "name": "Tech S",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "18",
      "managerId": "2",
      "name": "Tech T",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "19",
      "managerId": "2",
      "name": "Tech U",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "20",
      "managerId": "2",
      "name": "Tech V",
      "hpc": "3.15",
      "voc": "92.85",
      "atnd": "300",
      "aiq": "93.5"
    },
    {
      "id": "21",
      "managerId": "3",
      "name": "Tech W",
      "hpc": "2.98",
      "voc": "89",
      "atnd": "300",
      "aiq": "82"
    },
    {
      "id": "22",
      "managerId": "3",
      "name": "Tech X",
      "hpc": "2.98",
      "voc": "89",
      "atnd": "300",
      "aiq": "82"
    },
    {
      "id": "23",
      "managerId": "3",
      "name": "Tech Y",
      "hpc": "2.98",
      "voc": "89",
      "atnd": "300",
      "aiq": "82"
    },
    {
      "id": "24",
      "managerId": "3",
      "name": "Tech Z",
      "hpc": "2.98",
      "voc": "89",
      "atnd": "300",
      "aiq": "82"
    },
  ],
  "techHpc": [
    {
      "id": "1",
      "managerId": "1",
      "name": "Tech A",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "2",
      "managerId": "1",
      "name": "Tech B",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    }, {
      "id": "3",
      "managerId": "1",
      "name": "Tech C",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    }, {
      "id": "4",
      "managerId": "1",
      "name": "Tech D",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    }, {
      "id": "5",
      "managerId": "1",
      "name": "Tech E",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "6",
      "managerId": "1",
      "name": "Tech F",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "6",
      "managerId": "1",
      "name": "Tech G",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "7",
      "managerId": "1",
      "name": "Tech H",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "8",
      "managerId": "1",
      "name": "Tech I",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "9",
      "managerId": "1",
      "name": "Tech J",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "10",
      "managerId": "1",
      "name": "Tech K",
      "hpc": "2.98",
      "goal": "3.00",
      "variance": ".02",
      "varPercent": ".67",
      "de": "80",
      "productivity": "82",
    },
    {
      "id": "11",
      "managerId": "2",
      "name": "Tech L",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "12",
      "managerId": "2",
      "name": "Tech M",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "13",
      "managerId": "2",
      "name": "Tech N",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "14",
      "managerId": "2",
      "name": "Tech O",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "15",
      "managerId": "2",
      "name": "Tech P",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "16",
      "managerId": "2",
      "name": "Tech Q",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "16",
      "managerId": "2",
      "name": "Tech R",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "17",
      "managerId": "2",
      "name": "Tech S",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "18",
      "managerId": "2",
      "name": "Tech T",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "19",
      "managerId": "2",
      "name": "Tech U",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "20",
      "managerId": "2",
      "name": "Tech V",
      "hpc": "3.15",
      "goal": "2.90",
      "variance": "1.5",
      "varPercent": "4",
      "de": "86",
      "productivity": "92",
    },
    {
      "id": "21",
      "managerId": "3",
      "name": "Tech W",
      "hpc": "3",
      "goal": "2.15",
      "variance": "3.0",
      "varPercent": "10",
      "de": "77",
      "productivity": "75",
    },
    {
      "id": "22",
      "managerId": "3",
      "name": "Tech X",
      "hpc": "3",
      "goal": "2.15",
      "variance": "3.0",
      "varPercent": "10",
      "de": "77",
      "productivity": "75",
    },
    {
      "id": "23",
      "managerId": "3",
      "name": "Tech Y",
      "hpc": "3",
      "goal": "2.15",
      "variance": "3.0",
      "varPercent": "10",
      "de": "77",
      "productivity": "75",
    },
    {
      "id": "24",
      "managerId": "3",
      "name": "Tech Z",
      "hpc": "3",
      "goal": "2.15",
      "variance": "3.0",
      "varPercent": "10",
      "de": "77",
      "productivity": "75",
    },
  ]
}